spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/EpidemicSimulation
    username: postgres
    password: sa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 10000
        format_sql: true
    database: postgresql
  flyway:
    baseline-on-migrate: true

database:
  url: jdbc:postgresql://localhost:5432/EpidemicSimulation
  username: postgres
  password: sa
